### PR TITLE
Feat/db schema

### PR DESCRIPTION
**Pull request by aricalves**

### CODE REVIEW

**Comment by aricalves** [comment]
Whoops, give me a minute to rebase.

**Comment by aricalves** [comment]
[Create DB schema](https://trello.com/c/TSgP08C5/5-create-db-schema)

**Review by mikehern — DISMISSED** [review]
One thing to note is at some point, it'd be great to have price ranges for food and coffee, but this schema is perfectly fine for the first iteration.  Approved.

**Comment by aricalves** [comment]
~@mikehern I could grab the classic Yelp price metric ($ - $$$$) and save that as well. I'll make the change now to avoid adding a migration later~
done ✔️

**Review by angelahuang89 — APPROVED** [review]
Stupendous schema

**Pull request merged**
